### ISSUE TITLE
进入全屏签字，没能生成签字图片

### ISSUE THREAD

**Issue by tcfyvgbh** [linjc/mini-smooth-signature#7]
在微信小程序选择全屏签字的时候，getRotateImage方法旋转签字图片时 用到的wx.getFileSystemManager().writeFile({})方法传入的data应该去除DATA URI前缀[https://developers.weixin.qq.com/miniprogram/dev/api/file/FileSystemManager.writeFile.html](url)

**Comment by linjc** [comment]
@tcfyvgbh 样例里面去除前缀的那行代码还在，不过注释掉了，你可以重新使用看看。

**Comment by wapchief** [comment]
data.replace(/^data:image\/\w+;base64,/, "");
